app:
  version: '@project.version@'
  sensors:
    farm21:
      url: https://app.farm21.tech/api/v2/public/
      api-token: ${FARM21_API_TOKEN}
  scheduled:
    data-import:
      cron: "0 0 0 * * *" # every day at midnight
fiware:
  context-broker-url: ${CONTEXT_BROKER_URL}
logging:
  level:
    root: info
    de.app.fivegla: trace
    one.microstream: debug
    org.springframework.web.client.RestTemplate: debug
one:
  microstream:
    storage-directory: ${MICROSTREAM_STORAGE_DIRECTORY}
    channel-count: 2